version: '3.9'

services:
  mongo_db:
    image: mongo:latest
    hostname: mongo_db
    container_name: mongo_db
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword

  postgres_db:
    image: postgres:latest
    hostname: postgres_db
    container_name: postgres_db
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass}
      #POSTGRES_DB: ${POSTGRES_DB:-}

volumes:
  postgres_volume:
    driver: local
  mongo_volume:
    driver: local
